### PR TITLE
Fix Snagit Script License Issue

### PR DESCRIPTION
**Pull request by MLBZ521**
**Problem this fixes**:  The `postinstall` script is stored and updated in the parent recipe directory and due to how `TechSmithAddScriptKey.py` is written, once the `postinstall` script is updated once, it is never updated again if the license key is changed.  This also makes edits to the local git repo preventing `git pull` (and `autopkg`'s `autopkg repo-update bkerns-recipes`) from working.

**My experience**:  Every year when a new major version is released and our license key changes, new packages contain the old license...and I have to figure out, _again_, why the new license key isn't being used even though it's "in" the recipe as it should be...

While `TechSmithAddScriptKey.py` could be re-written to work, this simplifies this recipe with less moving parts.

Changes:
  * .pkg recipe:
    + Moved scripts into the recipe itself instead of a external files
    + Added a check to ensure the `SNAGIT_KEY` input variable has been overridden
    + Added clean up step as well
    - Removed unused files
  * .download recipe:
    - Removed duplicate processor step (`PlistReader`)
    + Moved `EndOfCheckPhase` after `CodeSignatureVerifier`

### CODE REVIEW

**Comment by MLBZ521** [comment]
Hey @kernsb, could you merge this if you have no issues with it?  I'm running into an [issue](https://github.com/grahampugh/jamf-upload/issues/160) when using JamfUploader to upload this package.

**Comment by MLBZ521** [comment]
@kernsb Just wanted to bump this and see if it could be merged?  Thanks

**Comment by MLBZ521** [comment]
Thanks!

**Comment by sdagley** [comment]
For sites that don't make use of a site license key merging this change has broken the .pkg recipe since it terminates without completing if there's no key.

**Comment by MLBZ521** [comment]
Ah.....I didn't think of someone not using a Site license.....

Let me throw together another PR to fix this.

**Comment by MLBZ521** [comment]
PR #44 submitted.  That should allow previous functionality.

**Pull request merged**
